services: 
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=planificateur
  planificateur-e2e:
    container_name: planificateur-e2e
    build:
      dockerfile: src/Planificateur.Web/Dockerfile
      context: ..
      
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=planificateur-test
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - JWT_SECRET=this-is-a-secret-dont-tell-anyone
    ports: 
      - 5000:80